-- MySQL Script generated by MySQL Workbench
-- Mon May  1 11:06:14 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wikipedia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wikipedia` ;

-- -----------------------------------------------------
-- Schema wikipedia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wikipedia` DEFAULT CHARACTER SET utf8 ;
USE `wikipedia` ;

-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_tipo_de_articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_tipo_de_articulos` (
  `CODIGO_TIPO_ARTICULO` INT(11) NOT NULL,
  `NOMBRE_TIPO_ARTICULO` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`CODIGO_TIPO_ARTICULO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tipo_proteccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tipo_proteccion` (
  `CODIGO_TIPO_PROTECCION` INT(11) NOT NULL,
  `NOMBRE_TIPO_PROTECCION` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`CODIGO_TIPO_PROTECCION`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_articulos` (
  `CODIGO_ARTICULO` INT(11) NOT NULL,
  `CODIGO_TIPO_PROTECCION` INT(11) NOT NULL,
  `CODIGO_TIPO_ARTICULO` INT(11) NOT NULL,
  `NOMBRE_ARTICULO` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`CODIGO_ARTICULO`, `CODIGO_TIPO_PROTECCION`, `CODIGO_TIPO_ARTICULO`),
  CONSTRAINT `ARTI_TIPO_DE_ARTI_FK`
    FOREIGN KEY (`CODIGO_TIPO_ARTICULO`)
    REFERENCES `wikipedia`.`tbl_tipo_de_articulos` (`CODIGO_TIPO_ARTICULO`),
  CONSTRAINT `ARTI_TIPO_PROTEC_ARCHIV_FK`
    FOREIGN KEY (`CODIGO_TIPO_PROTECCION`)
    REFERENCES `wikipedia`.`tipo_proteccion` (`CODIGO_TIPO_PROTECCION`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `ARTI_TIPO_DE_ARTI_FK` ON `wikipedia`.`tbl_articulos` (`CODIGO_TIPO_ARTICULO` ASC);

CREATE INDEX `ARTI_TIPO_PROTEC_ARCHIV_FK` ON `wikipedia`.`tbl_articulos` (`CODIGO_TIPO_PROTECCION` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`discusion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`discusion` (
  `CODIGO_ARTICULO` INT(11) NOT NULL COMMENT ' \n',
  PRIMARY KEY (`CODIGO_ARTICULO`),
  CONSTRAINT `DISCUSION_TBL_ARTICULOS_FK`
    FOREIGN KEY (`CODIGO_ARTICULO`)
    REFERENCES `wikipedia`.`tbl_articulos` (`CODIGO_ARTICULO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `DISCUSION__UN` ON `wikipedia`.`discusion` (`CODIGO_ARTICULO` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_generos` (
  `CODIGO_GENERO` INT(11) NOT NULL,
  `NOMBRE_GENERO` VARCHAR(200) NOT NULL,
  `ABREVIATURA_GENERO` VARCHAR(5) NULL DEFAULT NULL COMMENT 'ABREV',
  PRIMARY KEY (`CODIGO_GENERO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_husos_horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_husos_horarios` (
  `CODIGO_HUSO_HORARIO` INT(11) NOT NULL,
  `NOMBRE_HUSO_HORARIO` VARCHAR(200) NOT NULL,
  `HORA` DATETIME NOT NULL,
  PRIMARY KEY (`CODIGO_HUSO_HORARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_tipo_lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_tipo_lugar` (
  `CODIGO_TIPO_LUGAR` INT(11) NOT NULL,
  `NOMBRE_TIPO_LUGAR` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`CODIGO_TIPO_LUGAR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_lugares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_lugares` (
  `CODIGO_LUGAR` INT(11) NOT NULL,
  `CODIGO_LUGAR_PADRE` INT(11) NULL DEFAULT NULL,
  `CODIGO_TIPO_LUGAR` INT(11) NOT NULL,
  `CODIGO_ARTICULO` INT(11) NOT NULL,
  `NOMBRE_LUGAR` VARCHAR(200) NOT NULL,
  `LATITUD` DOUBLE NULL DEFAULT NULL,
  `LONGITUD` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO_LUGAR`, `CODIGO_TIPO_LUGAR`, `CODIGO_ARTICULO`),
  CONSTRAINT `TBL_LUGARES_TBL_ARTICULOS_FK`
    FOREIGN KEY (`CODIGO_ARTICULO`)
    REFERENCES `wikipedia`.`tbl_articulos` (`CODIGO_ARTICULO`),
  CONSTRAINT `TBL_LUGARES_TBL_LUGARES_FK`
    FOREIGN KEY (`CODIGO_LUGAR_PADRE`)
    REFERENCES `wikipedia`.`tbl_lugares` (`CODIGO_LUGAR`),
  CONSTRAINT `TBL_LUGARES_TBL_TIPO_LUGAR_FK`
    FOREIGN KEY (`CODIGO_TIPO_LUGAR`)
    REFERENCES `wikipedia`.`tbl_tipo_lugar` (`CODIGO_TIPO_LUGAR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `TBL_LUGARES_TBL_ARTICULOS_FK` ON `wikipedia`.`tbl_lugares` (`CODIGO_ARTICULO` ASC);

CREATE INDEX `TBL_LUGARES_TBL_LUGARES_FK` ON `wikipedia`.`tbl_lugares` (`CODIGO_LUGAR_PADRE` ASC);

CREATE INDEX `TBL_LUGARES_TBL_TIPO_LUGAR_FK` ON `wikipedia`.`tbl_lugares` (`CODIGO_TIPO_LUGAR` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_tipos_de_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_tipos_de_usuarios` (
  `CODIGO_TIPO_USUARIO` INT(11) NOT NULL,
  `NOMBRE_TIPO_USUARIO` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO_TIPO_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_usuarios` (
  `CODIGO_USUARIO` INT(11) NOT NULL,
  `CODIGO_GENERO` INT(11) NOT NULL,
  `CODIGO_LUGAR_RESIDENCIA` INT(11) NULL DEFAULT NULL,
  `CODIGO_LUGAR_NACIMIENTO` INT(11) NULL DEFAULT NULL,
  `CODIGO_TIPO_USUARIO` INT(11) NOT NULL,
  `CODIGO_ARTICULO_USUARIO` INT(11) NULL DEFAULT NULL COMMENT 'ES EL ARTICULO QUE SE CREA CUANDO SE REGISTRA UN NUEVO USUARIO. CONTIENE INFORMACION SOBRE LOS APORTES QUE HA HECHO A LA PAGINA DE WIKIPEDIA.',
  `CODIGO_HUSO_HORARIO` INT(11) NULL DEFAULT NULL,
  `USERNAME` VARCHAR(100) NULL DEFAULT NULL COMMENT 'NOMBRE CON EL CUAL SE IDENTIFICA AL USUARIO EN WIKIPEDIA. SE UTILIZA PARA ENTRAR A CUENTA.',
  `NOMBRE` VARCHAR(200) NULL DEFAULT NULL COMMENT 'NOMBRE REAL DEL USUARIO',
  `APELLIDO` VARCHAR(200) NULL DEFAULT NULL COMMENT 'APELLIDO DEL USUARIO',
  `CORREO_ELECTRONICO` VARCHAR(200) NULL DEFAULT NULL COMMENT 'CORREO ELECTRONICO PARA ENVIAR NOTIFICIONES O RECUPERAR CUENTA. NO ES OBLIGATORIO.',
  `CONTRASEÑA` VARCHAR(50) NULL DEFAULT NULL COMMENT 'CLAVE PARA ENTRAR A CUENTA',
  `FECHA_NACIMIENTO` DATETIME NULL DEFAULT NULL,
  `DIRECCION_IP` VARCHAR(50) NOT NULL COMMENT 'SE UITLIZA PARA IDENTIFICAR A LOS USUARIOS NO REGISTRADOS.',
  `NUMERO_FALTAS` INT(11) NOT NULL,
  PRIMARY KEY (`CODIGO_USUARIO`, `CODIGO_TIPO_USUARIO`),
  CONSTRAINT `USUARIOS_ARTICULOS_FK`
    FOREIGN KEY (`CODIGO_ARTICULO_USUARIO`)
    REFERENCES `wikipedia`.`tbl_articulos` (`CODIGO_ARTICULO`),
  CONSTRAINT `USUARIOS_GENEROS_FK`
    FOREIGN KEY (`CODIGO_GENERO`)
    REFERENCES `wikipedia`.`tbl_generos` (`CODIGO_GENERO`),
  CONSTRAINT `USUARIOS_HUSOS_HOR_FK`
    FOREIGN KEY (`CODIGO_HUSO_HORARIO`)
    REFERENCES `wikipedia`.`tbl_husos_horarios` (`CODIGO_HUSO_HORARIO`),
  CONSTRAINT `USUARIOS_LUGARES_FK`
    FOREIGN KEY (`CODIGO_LUGAR_NACIMIENTO`)
    REFERENCES `wikipedia`.`tbl_lugares` (`CODIGO_LUGAR`),
  CONSTRAINT `USUARIOS_LUGARES_FKv2`
    FOREIGN KEY (`CODIGO_LUGAR_RESIDENCIA`)
    REFERENCES `wikipedia`.`tbl_lugares` (`CODIGO_LUGAR`),
  CONSTRAINT `USUA_TIPOS_DE_USUA_FK`
    FOREIGN KEY (`CODIGO_TIPO_USUARIO`)
    REFERENCES `wikipedia`.`tbl_tipos_de_usuarios` (`CODIGO_TIPO_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `TBL_USUARIOS__UN` ON `wikipedia`.`tbl_usuarios` (`USERNAME` ASC);

CREATE INDEX `USUARIOS_ARTICULOS_FK` ON `wikipedia`.`tbl_usuarios` (`CODIGO_ARTICULO_USUARIO` ASC);

CREATE INDEX `USUARIOS_GENEROS_FK` ON `wikipedia`.`tbl_usuarios` (`CODIGO_GENERO` ASC);

CREATE INDEX `USUARIOS_HUSOS_HOR_FK` ON `wikipedia`.`tbl_usuarios` (`CODIGO_HUSO_HORARIO` ASC);

CREATE INDEX `USUARIOS_LUGARES_FK` ON `wikipedia`.`tbl_usuarios` (`CODIGO_LUGAR_NACIMIENTO` ASC);

CREATE INDEX `USUARIOS_LUGARES_FKv2` ON `wikipedia`.`tbl_usuarios` (`CODIGO_LUGAR_RESIDENCIA` ASC);

CREATE INDEX `USUA_TIPOS_DE_USUA_FK` ON `wikipedia`.`tbl_usuarios` (`CODIGO_TIPO_USUARIO` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`donaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`donaciones` (
  `CODIGO_DONACION` INT(11) NOT NULL,
  `CODIGO_USUARIO` INT(11) NULL DEFAULT NULL,
  `MONTO` DOUBLE NULL DEFAULT NULL,
  `FECHA` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO_DONACION`),
  CONSTRAINT `DONACIONES_USUARIOS_FK`
    FOREIGN KEY (`CODIGO_USUARIO`)
    REFERENCES `wikipedia`.`tbl_usuarios` (`CODIGO_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `DONACIONES_USUARIOS_FK` ON `wikipedia`.`donaciones` (`CODIGO_USUARIO` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_secciones` (
  `CODIGO_SECCION` INT(11) NOT NULL,
  `CODIGO_ARTICULO` INT(11) NOT NULL,
  `NOMBRE_SECCION` VARCHAR(4000) NULL DEFAULT NULL,
  `CONTENIDO_TEXTUAL` LONGTEXT NOT NULL,
  PRIMARY KEY (`CODIGO_SECCION`, `CODIGO_ARTICULO`),
  CONSTRAINT `TBL_SECCIONES_TBL_ARTICULOS_FK`
    FOREIGN KEY (`CODIGO_ARTICULO`)
    REFERENCES `wikipedia`.`tbl_articulos` (`CODIGO_ARTICULO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `TBL_SECCIONES_TBL_ARTICULOS_FK` ON `wikipedia`.`tbl_secciones` (`CODIGO_ARTICULO` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_archivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_archivos` (
  `CODIGO_ARCHIVO` INT(11) NOT NULL,
  `CODIGO_SECCION` INT(11) NOT NULL,
  `NOMBRE_ARCHIVO` VARCHAR(200) NOT NULL,
  `TAMAÑO_ARCHIVO` DOUBLE NOT NULL COMMENT 'SE REFIERE AL PESO DEL ARCHIVO',
  `DESCRIPCION` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`CODIGO_ARCHIVO`, `CODIGO_SECCION`),
  CONSTRAINT `ARCHIL_SECCIONES_FK`
    FOREIGN KEY (`CODIGO_SECCION`)
    REFERENCES `wikipedia`.`tbl_secciones` (`CODIGO_SECCION`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `ARCHIL_SECCIONES_FK` ON `wikipedia`.`tbl_archivos` (`CODIGO_SECCION` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_articulos_relacionados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_articulos_relacionados` (
  `CODIGO_ARTICULO_1` INT(11) NOT NULL,
  `CODIGO_ARTICULO_2` INT(11) NOT NULL,
  PRIMARY KEY (`CODIGO_ARTICULO_2`, `CODIGO_ARTICULO_1`),
  CONSTRAINT `ARTI_RELACI_ARTICULOS_FKv2`
    FOREIGN KEY (`CODIGO_ARTICULO_2`)
    REFERENCES `wikipedia`.`tbl_articulos` (`CODIGO_ARTICULO`),
  CONSTRAINT `ARTI_RELAC_ARTICULOS_FK`
    FOREIGN KEY (`CODIGO_ARTICULO_1`)
    REFERENCES `wikipedia`.`tbl_articulos` (`CODIGO_ARTICULO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `ARTI_RELAC_ARTICULOS_FK` ON `wikipedia`.`tbl_articulos_relacionados` (`CODIGO_ARTICULO_1` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_categorias` (
  `CODIGO_CATEGORIA` INT(11) NOT NULL,
  `NOMBRE_CATEGORIA` VARCHAR(300) NOT NULL,
  `NUMERO_ARTICULOS` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO_CATEGORIA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_articulos_x_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_articulos_x_categorias` (
  `CODIGO_CATEGORIA` INT(11) NOT NULL,
  `CODIGO_ARTICULO` INT(11) NOT NULL,
  PRIMARY KEY (`CODIGO_ARTICULO`, `CODIGO_CATEGORIA`),
  CONSTRAINT `ARTI_X_CATEG_CATEG_FK`
    FOREIGN KEY (`CODIGO_CATEGORIA`)
    REFERENCES `wikipedia`.`tbl_categorias` (`CODIGO_CATEGORIA`),
  CONSTRAINT `ARTI_X_CATEG_TBL_ARTIC_FK`
    FOREIGN KEY (`CODIGO_ARTICULO`)
    REFERENCES `wikipedia`.`tbl_articulos` (`CODIGO_ARTICULO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `ARTI_X_CATEG_CATEG_FK` ON `wikipedia`.`tbl_articulos_x_categorias` (`CODIGO_CATEGORIA` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_audio` (
  `CODIGO_AUDIO` INT(11) NOT NULL,
  `DURACION` VARCHAR(100) NOT NULL,
  `AUDIO` LONGBLOB NOT NULL,
  PRIMARY KEY (`CODIGO_AUDIO`),
  CONSTRAINT `VIDEOS_TBL_ARCHIVOS_FK`
    FOREIGN KEY (`CODIGO_AUDIO`)
    REFERENCES `wikipedia`.`tbl_archivos` (`CODIGO_ARCHIVO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_comentarios` (
  `CODIGO_COMENTARIO` INT(11) NOT NULL COMMENT ' \n',
  `CODIGO_USUARIO` INT(11) NOT NULL COMMENT ' \n',
  `CODIGO_ARTICULO` INT(11) NOT NULL COMMENT ' \n',
  `COMENTARIO` VARCHAR(2000) NOT NULL COMMENT ' \n',
  PRIMARY KEY (`CODIGO_COMENTARIO`, `CODIGO_USUARIO`, `CODIGO_ARTICULO`),
  CONSTRAINT `COMENT_DISCUSION_FK`
    FOREIGN KEY (`CODIGO_ARTICULO`)
    REFERENCES `wikipedia`.`discusion` (`CODIGO_ARTICULO`),
  CONSTRAINT `COMENT_USUARIOS_FK`
    FOREIGN KEY (`CODIGO_USUARIO`)
    REFERENCES `wikipedia`.`tbl_usuarios` (`CODIGO_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `COMENT_DISCUSION_FK` ON `wikipedia`.`tbl_comentarios` (`CODIGO_ARTICULO` ASC);

CREATE INDEX `COMENT_USUARIOS_FK` ON `wikipedia`.`tbl_comentarios` (`CODIGO_USUARIO` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_cuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_cuentas` (
  `CODIGO_CUENTA` INT(11) NOT NULL,
  `CODIGO_USUARIO` INT(11) NOT NULL,
  `NUMERO_EDICIONES` INT(11) NULL DEFAULT NULL,
  `FECHA_REGISTRO` DATETIME NOT NULL,
  PRIMARY KEY (`CODIGO_CUENTA`, `CODIGO_USUARIO`),
  CONSTRAINT `CUENTAS_USUARIOS_FK`
    FOREIGN KEY (`CODIGO_USUARIO`)
    REFERENCES `wikipedia`.`tbl_usuarios` (`CODIGO_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `CUENTAS_USUARIOS_FK` ON `wikipedia`.`tbl_cuentas` (`CODIGO_USUARIO` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_estado_notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_estado_notificaciones` (
  `CODIGO_ESTADO` INT(11) NOT NULL,
  `NOMBRE_ESTADO` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`CODIGO_ESTADO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_estados_prefrencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_estados_prefrencias` (
  `CODIGO_ESTADO_PREFERENCIA` INT(11) NOT NULL,
  `NOMBRE_ESTADO` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`CODIGO_ESTADO_PREFERENCIA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_historial_articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_historial_articulo` (
  `CODIGO_EDITOR` INT(11) NOT NULL,
  `CODIGO_SECCION` INT(11) NOT NULL,
  `FECHA_EDICION` DATETIME NOT NULL,
  `CONTENIDO` LONGTEXT NOT NULL,
  PRIMARY KEY (`CODIGO_EDITOR`, `CODIGO_SECCION`),
  CONSTRAINT `ARTI_X_USU_SECCIONES_FK`
    FOREIGN KEY (`CODIGO_SECCION`)
    REFERENCES `wikipedia`.`tbl_secciones` (`CODIGO_SECCION`),
  CONSTRAINT `SECCI_X_USUAR_CUENTAS_FK`
    FOREIGN KEY (`CODIGO_EDITOR`)
    REFERENCES `wikipedia`.`tbl_cuentas` (`CODIGO_CUENTA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `ARTI_X_USU_SECCIONES_FK` ON `wikipedia`.`tbl_historial_articulo` (`CODIGO_SECCION` ASC);

CREATE INDEX `SECCI_X_USUAR_CUENTAS_FK` ON `wikipedia`.`tbl_historial_articulo` (`CODIGO_EDITOR` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_tipo_faltas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_tipo_faltas` (
  `CODIGO_TIPO_FALTA` INT(11) NOT NULL,
  `NOMBRE_TIPO_FALTA` VARCHAR(50) NULL DEFAULT NULL,
  `DESCRIPCION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO_TIPO_FALTA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_sanciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_sanciones` (
  `CODIGO_SANCION` INT(11) NOT NULL,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `DESCRIPCION` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CODIGO_SANCION`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_historial_faltas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_historial_faltas` (
  `CODIGO_USUARIO` INT(11) NOT NULL,
  `CODIGO_TIPO_FALTA` INT(11) NOT NULL,
  `CODIGO_SANCION` INT(11) NOT NULL,
  `FECHA_FALTA` DATETIME NOT NULL,
  PRIMARY KEY (`CODIGO_TIPO_FALTA`, `CODIGO_SANCION`, `CODIGO_USUARIO`),
  CONSTRAINT `FALTASL_USUARIOS_FK`
    FOREIGN KEY (`CODIGO_USUARIO`)
    REFERENCES `wikipedia`.`tbl_usuarios` (`CODIGO_USUARIO`),
  CONSTRAINT `FALTAS_TIPO_FALTAS_FK`
    FOREIGN KEY (`CODIGO_TIPO_FALTA`)
    REFERENCES `wikipedia`.`tbl_tipo_faltas` (`CODIGO_TIPO_FALTA`),
  CONSTRAINT `HISTOR_FALTASL_SANCIONES_FK`
    FOREIGN KEY (`CODIGO_SANCION`)
    REFERENCES `wikipedia`.`tbl_sanciones` (`CODIGO_SANCION`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FALTASL_USUARIOS_FK` ON `wikipedia`.`tbl_historial_faltas` (`CODIGO_USUARIO` ASC);

CREATE INDEX `FALTAS_TIPO_FALTAS_FK` ON `wikipedia`.`tbl_historial_faltas` (`CODIGO_TIPO_FALTA` ASC);

CREATE INDEX `HISTOR_FALTASL_SANCIONES_FK` ON `wikipedia`.`tbl_historial_faltas` (`CODIGO_SANCION` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_idiomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_idiomas` (
  `CODIGO_IDIOMA` INT(11) NOT NULL,
  `CODIGO_ARTICULO` INT(11) NOT NULL,
  `NOMBRE_IDIOMA` VARCHAR(200) NOT NULL,
  `NUMERO_ARTICULOS` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO_IDIOMA`),
  CONSTRAINT `IDIOM_TBL_ARTICULOS_FK`
    FOREIGN KEY (`CODIGO_ARTICULO`)
    REFERENCES `wikipedia`.`tbl_articulos` (`CODIGO_ARTICULO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `IDIOM_TBL_ARTICULOS_FK` ON `wikipedia`.`tbl_idiomas` (`CODIGO_ARTICULO` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_idiomas_relacionados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_idiomas_relacionados` (
  `CODIGO_IDIOMA` INT(11) NOT NULL,
  `CODIGO_IDIOMA_RELACIONADO` INT(11) NOT NULL,
  PRIMARY KEY (`CODIGO_IDIOMA`, `CODIGO_IDIOMA_RELACIONADO`),
  CONSTRAINT `IDIOM_RELAC_IDIOMAS_FK`
    FOREIGN KEY (`CODIGO_IDIOMA`)
    REFERENCES `wikipedia`.`tbl_idiomas` (`CODIGO_IDIOMA`),
  CONSTRAINT `IDIOM_RELAC_IDIOMAS_FKv2`
    FOREIGN KEY (`CODIGO_IDIOMA_RELACIONADO`)
    REFERENCES `wikipedia`.`tbl_idiomas` (`CODIGO_IDIOMA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `IDIOM_RELAC_IDIOMAS_FKv2` ON `wikipedia`.`tbl_idiomas_relacionados` (`CODIGO_IDIOMA_RELACIONADO` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_imagenes` (
  `CODIGO_IMAGEN` INT(11) NOT NULL,
  `ANCHURA` INT(11) NOT NULL,
  `LONGITUD` INT(11) NOT NULL,
  `IMAGEN` LONGBLOB NOT NULL,
  PRIMARY KEY (`CODIGO_IMAGEN`),
  CONSTRAINT `TBL_IMAGENES_TBL_ARCHIVOS_FK`
    FOREIGN KEY (`CODIGO_IMAGEN`)
    REFERENCES `wikipedia`.`tbl_archivos` (`CODIGO_ARCHIVO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_instituciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_instituciones` (
  `CODIGO_INSTITUCION` INT(11) NOT NULL,
  `CODIGO_LUGAR` INT(11) NOT NULL,
  `NOMBRE_INSTITUCION` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`CODIGO_INSTITUCION`, `CODIGO_LUGAR`),
  CONSTRAINT `TBL_INSTI_TBL_LUGARES_FK`
    FOREIGN KEY (`CODIGO_LUGAR`)
    REFERENCES `wikipedia`.`tbl_lugares` (`CODIGO_LUGAR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `TBL_INSTI_TBL_LUGARES_FK` ON `wikipedia`.`tbl_instituciones` (`CODIGO_LUGAR` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_listas_seguimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_listas_seguimiento` (
  `CODIGO_USUARIO` INT(11) NOT NULL,
  `CODIGO_ARTICULO` INT(11) NOT NULL,
  `FECHA_AGREGADO` DATETIME NOT NULL,
  `CODIGO_CUENTA` INT(11) NOT NULL,
  PRIMARY KEY (`CODIGO_ARTICULO`, `CODIGO_USUARIO`, `CODIGO_CUENTA`),
  CONSTRAINT `LISTAS_SEGUI_TBL_ARTICULOS_FK`
    FOREIGN KEY (`CODIGO_ARTICULO`)
    REFERENCES `wikipedia`.`tbl_articulos` (`CODIGO_ARTICULO`),
  CONSTRAINT `LISTAS_SEGUI_TBL_CUENTAS_FK`
    FOREIGN KEY (`CODIGO_CUENTA`)
    REFERENCES `wikipedia`.`tbl_cuentas` (`CODIGO_CUENTA`),
  CONSTRAINT `LISTAS_SEGU_TBL_USUARIOS_FK`
    FOREIGN KEY (`CODIGO_USUARIO`)
    REFERENCES `wikipedia`.`tbl_usuarios` (`CODIGO_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `LISTAS_SEGUI_TBL_CUENTAS_FK` ON `wikipedia`.`tbl_listas_seguimiento` (`CODIGO_CUENTA` ASC);

CREATE INDEX `LISTAS_SEGU_TBL_USUARIOS_FK` ON `wikipedia`.`tbl_listas_seguimiento` (`CODIGO_USUARIO` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_tipos_notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_tipos_notificaciones` (
  `CODIGO_TIPO_NOTIFICACION` INT(11) NOT NULL,
  `NOMBRE_TIPO_NOTIFICACION` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`CODIGO_TIPO_NOTIFICACION`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_notificaciones` (
  `CODIGO_NOTIFICACION` INT(11) NOT NULL,
  `CODIGO_USUARIO_EMISOR` INT(11) NOT NULL,
  `CODIGO_USUARIO_RECEPTOR` INT(11) NOT NULL,
  `CODIGO_TIPO_NOTIFICACION` INT(11) NOT NULL,
  `CODIGO_ESTADO` INT(11) NOT NULL,
  PRIMARY KEY (`CODIGO_NOTIFICACION`, `CODIGO_USUARIO_EMISOR`, `CODIGO_USUARIO_RECEPTOR`, `CODIGO_TIPO_NOTIFICACION`, `CODIGO_ESTADO`),
  CONSTRAINT `NOTIFIC_ESTADO_NOTIFIC_FK`
    FOREIGN KEY (`CODIGO_ESTADO`)
    REFERENCES `wikipedia`.`tbl_estado_notificaciones` (`CODIGO_ESTADO`),
  CONSTRAINT `NOTIFIC_TBL_USUARIOS_FK`
    FOREIGN KEY (`CODIGO_USUARIO_EMISOR`)
    REFERENCES `wikipedia`.`tbl_usuarios` (`CODIGO_USUARIO`),
  CONSTRAINT `NOTIFIC_TBL_USUARIOS_FKv2`
    FOREIGN KEY (`CODIGO_USUARIO_RECEPTOR`)
    REFERENCES `wikipedia`.`tbl_usuarios` (`CODIGO_USUARIO`),
  CONSTRAINT `NOTIFIC_TIPOS_NOTIFIC_FK`
    FOREIGN KEY (`CODIGO_TIPO_NOTIFICACION`)
    REFERENCES `wikipedia`.`tbl_tipos_notificaciones` (`CODIGO_TIPO_NOTIFICACION`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `NOTIFIC_ESTADO_NOTIFIC_FK` ON `wikipedia`.`tbl_notificaciones` (`CODIGO_ESTADO` ASC);

CREATE INDEX `NOTIFIC_TBL_USUARIOS_FK` ON `wikipedia`.`tbl_notificaciones` (`CODIGO_USUARIO_EMISOR` ASC);

CREATE INDEX `NOTIFIC_TBL_USUARIOS_FKv2` ON `wikipedia`.`tbl_notificaciones` (`CODIGO_USUARIO_RECEPTOR` ASC);

CREATE INDEX `NOTIFIC_TIPOS_NOTIFIC_FK` ON `wikipedia`.`tbl_notificaciones` (`CODIGO_TIPO_NOTIFICACION` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_portales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_portales` (
  `CODIGO_PORTAL` INT(11) NOT NULL,
  `NOMBRE_PORTAL` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`CODIGO_PORTAL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_portales_x_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_portales_x_categoria` (
  `CODIGO_PORTAL` INT(11) NOT NULL,
  `CODIGO_CATEGORIA` INT(11) NOT NULL,
  PRIMARY KEY (`CODIGO_PORTAL`, `CODIGO_CATEGORIA`),
  CONSTRAINT `PORT_X_CATEG_CATEGORIAS_FK`
    FOREIGN KEY (`CODIGO_CATEGORIA`)
    REFERENCES `wikipedia`.`tbl_categorias` (`CODIGO_CATEGORIA`),
  CONSTRAINT `PORT_X_CATEG_PORTALES_FK`
    FOREIGN KEY (`CODIGO_PORTAL`)
    REFERENCES `wikipedia`.`tbl_portales` (`CODIGO_PORTAL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `PORT_X_CATEG_CATEGORIAS_FK` ON `wikipedia`.`tbl_portales_x_categoria` (`CODIGO_CATEGORIA` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_tipos_preferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_tipos_preferencias` (
  `CODIGO_TIPO_PREFRENCIA` INT(11) NOT NULL,
  `NOMBRE_TIPO_PREFRENCIA` VARCHAR(200) NULL DEFAULT NULL,
  `CODIGO_PREFRENCIA_PADRE` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO_TIPO_PREFRENCIA`),
  CONSTRAINT `TIP_PREFER_TIP_PREFER_FK`
    FOREIGN KEY (`CODIGO_PREFRENCIA_PADRE`)
    REFERENCES `wikipedia`.`tbl_tipos_preferencias` (`CODIGO_TIPO_PREFRENCIA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `TIP_PREFER_TIP_PREFER_FK` ON `wikipedia`.`tbl_tipos_preferencias` (`CODIGO_PREFRENCIA_PADRE` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_preferencias_x_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_preferencias_x_usuarios` (
  `CODIGO_TIPO_PREFRENCIA` INT(11) NOT NULL,
  `CODIGO_USUARIO` INT(11) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NOT NULL,
  `CODIGO_ESTADO_PREFERENCIA` INT(11) NOT NULL,
  PRIMARY KEY (`CODIGO_TIPO_PREFRENCIA`, `CODIGO_USUARIO`, `CODIGO_ESTADO_PREFERENCIA`),
  CONSTRAINT `PREFER_TIPOS_PREFER_FK`
    FOREIGN KEY (`CODIGO_TIPO_PREFRENCIA`)
    REFERENCES `wikipedia`.`tbl_tipos_preferencias` (`CODIGO_TIPO_PREFRENCIA`),
  CONSTRAINT `PREFER_X_USUA_TBL_USUA_FK`
    FOREIGN KEY (`CODIGO_USUARIO`)
    REFERENCES `wikipedia`.`tbl_usuarios` (`CODIGO_USUARIO`),
  CONSTRAINT `PREFE_X_USUAR_ESTADOS_PREFR_FK`
    FOREIGN KEY (`CODIGO_ESTADO_PREFERENCIA`)
    REFERENCES `wikipedia`.`tbl_estados_prefrencias` (`CODIGO_ESTADO_PREFERENCIA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `PREFER_X_USUA_TBL_USUA_FK` ON `wikipedia`.`tbl_preferencias_x_usuarios` (`CODIGO_USUARIO` ASC);

CREATE INDEX `PREFE_X_USUAR_ESTADOS_PREFR_FK` ON `wikipedia`.`tbl_preferencias_x_usuarios` (`CODIGO_ESTADO_PREFERENCIA` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_reporte_errores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_reporte_errores` (
  `CODIGO_REPORTE_ERROR` INT(11) NOT NULL,
  `CODIGO_USER_REPORTA` INT(11) NOT NULL,
  `CODIGO_ARTICULO` INT(11) NOT NULL,
  `NOMBRE_ERROR` VARCHAR(200) NOT NULL,
  `DESCRIPCION` VARCHAR(4000) NOT NULL,
  `FECHA` DATETIME NOT NULL,
  PRIMARY KEY (`CODIGO_REPORTE_ERROR`, `CODIGO_USER_REPORTA`, `CODIGO_ARTICULO`),
  CONSTRAINT `REPOR_ERROR_ARTICULOS_FK`
    FOREIGN KEY (`CODIGO_ARTICULO`)
    REFERENCES `wikipedia`.`tbl_articulos` (`CODIGO_ARTICULO`),
  CONSTRAINT `REPOR_ERROR_USUARIOS_FK`
    FOREIGN KEY (`CODIGO_USER_REPORTA`)
    REFERENCES `wikipedia`.`tbl_usuarios` (`CODIGO_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `REPOR_ERROR_ARTICULOS_FK` ON `wikipedia`.`tbl_reporte_errores` (`CODIGO_ARTICULO` ASC);

CREATE INDEX `REPOR_ERROR_USUARIOS_FK` ON `wikipedia`.`tbl_reporte_errores` (`CODIGO_USER_REPORTA` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_tipo_cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_tipo_cuenta` (
  `CODIGO_TIPO_CUENTA` INT(11) NOT NULL,
  `CODIGO_CUENTA` INT(11) NOT NULL,
  `CODIGO_IDIOMA` INT(11) NOT NULL,
  `NOMBRE_TIPO_CUENTA` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CODIGO_TIPO_CUENTA`, `CODIGO_IDIOMA`, `CODIGO_CUENTA`),
  CONSTRAINT `TIPO_CUENTAL_CUENTAS_FK`
    FOREIGN KEY (`CODIGO_CUENTA`)
    REFERENCES `wikipedia`.`tbl_cuentas` (`CODIGO_CUENTA`),
  CONSTRAINT `TIPO_CUENTA_TBL_IDIOMAS_FK`
    FOREIGN KEY (`CODIGO_IDIOMA`)
    REFERENCES `wikipedia`.`tbl_idiomas` (`CODIGO_IDIOMA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `TIPO_CUENTAL_CUENTAS_FK` ON `wikipedia`.`tbl_tipo_cuenta` (`CODIGO_CUENTA` ASC);

CREATE INDEX `TIPO_CUENTA_TBL_IDIOMAS_FK` ON `wikipedia`.`tbl_tipo_cuenta` (`CODIGO_IDIOMA` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_tipos_de_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_tipos_de_permisos` (
  `CODIGO_TIPO_PERMISO` INT(11) NOT NULL,
  `NOMBRE_TIPO_PERMISO` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO_TIPO_PERMISO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_usuarios_x_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_usuarios_x_permisos` (
  `CODIGO_TIPO_PERMISO` INT(11) NOT NULL,
  `CODIGO_USUARIO` INT(11) NOT NULL,
  `FECHA_OBTENCION_PERMISO` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO_TIPO_PERMISO`, `CODIGO_USUARIO`),
  CONSTRAINT `USUA_PERMISOS_TIPOS__FK`
    FOREIGN KEY (`CODIGO_TIPO_PERMISO`)
    REFERENCES `wikipedia`.`tbl_tipos_de_permisos` (`CODIGO_TIPO_PERMISO`),
  CONSTRAINT `USUA_PERMISOS_USUA_FK`
    FOREIGN KEY (`CODIGO_USUARIO`)
    REFERENCES `wikipedia`.`tbl_usuarios` (`CODIGO_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `USUA_PERMISOS_USUA_FK` ON `wikipedia`.`tbl_usuarios_x_permisos` (`CODIGO_USUARIO` ASC);


-- -----------------------------------------------------
-- Table `wikipedia`.`tbl_visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedia`.`tbl_visitas` (
  `FECHA` DATETIME NULL DEFAULT NULL,
  `CODIGO_ARTICULO` INT(11) NOT NULL COMMENT 'CAMPO QUE ALMACENA LA FECHA  EN QUE SE VISITA UN ARTICULO',
  PRIMARY KEY (`CODIGO_ARTICULO`),
  CONSTRAINT `VISUALIZ_ARTICULOS_FK`
    FOREIGN KEY (`CODIGO_ARTICULO`)
    REFERENCES `wikipedia`.`tbl_articulos` (`CODIGO_ARTICULO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `VISUALIZ_ARTICULOS_FK` ON `wikipedia`.`tbl_visitas` (`CODIGO_ARTICULO` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
